### PR TITLE
PHP 8 support

### PR DESCRIPTION
**Pull request by maicol07**
Added PHP 8 support (**Needs testing**)

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

### CODE REVIEW

**Review by Majkl578 — APPROVED** [review]

**Review by olivernybroe — APPROVED** [review]

**Comment by olivernybroe** [comment]
It could be really awesome to get this merged in 👍 
It's blocked everyone for upgrading to php 8

**Comment by luisuribe** [comment]
Thanks, I'll be looking at this ASAP.

**Comment by aaronhuisinga** [comment]
Thanks @luisuribe. We're waiting on this package as well to update to PHP 8!

**Comment by olivernybroe** [comment]
Amazing! thanks for making a release. 

I was running with our own fork for this release in a month now on production and no issues for us at all.

**Pull request merged**
